services:

  # ================= DATABASE =================
  mysql:
    image: mysql:8.0
    container_name: evp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: video_platform
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # ================= CACHE =================
  redis:
    image: redis:7
    container_name: evp-redis
    ports:
      - "6379:6379"

  # ================= KAFKA =================
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  # ================= STORAGE (S3 LOCAL) =================
  minio:
    image: minio/minio
    container_name: evp-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"

  # ================= SEARCH =================
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  # ================= AUTH SERVICE =================
  auth-service:
    build: ./apps/auth-service
    container_name: evp-auth
    ports:
      - "4001:4001"
    env_file:
      - ./apps/auth-service/.env
    depends_on:
      - mysql # ✅ FIXED
    restart: always

volumes:
  mysql_data:
