apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      containers:
        - name: video-service
          image: video-service:latest
          ports:
            - containerPort: 4002
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: video-service
spec:
  type: ClusterIP
  selector:
    app: video-service
  ports:
    - port: 4002
      targetPort: 4002